// Generated by Dagger (https://google.github.io/dagger).
package com.example.didaktikapp.di.component;

import com.example.didaktikapp.di.modules.AppModule;
import com.example.didaktikapp.di.modules.DataSourceModule;
import com.example.didaktikapp.features.FullscreenActivity;
import com.example.didaktikapp.features.gameover.GameOverActivity;
import com.example.didaktikapp.features.gameplay.GamePlayActivity;
import com.example.didaktikapp.features.mainmenu.MainMenuActivity;
import com.google.android.gms.common.internal.Preconditions;


public final class DaggerAppComponent implements AppComponent {


  public DaggerAppComponent(Builder builder) {
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public void inject(GamePlayActivity activity) {

  }

  @Override
  public void inject(MainMenuActivity activity) {

  }

  @Override
  public void inject(GameOverActivity activity) {

  }

  @Override
  public void inject(FullscreenActivity activity) {

  }

  @Override
  public void inject(GameHistoryActivity activity) {

  }

  public static final class Builder {
    private AppModule appModule;

    private DataSourceModule dataSourceModule;

    private Builder() {}

    public AppComponent build() {
      if (appModule == null) {
        throw new IllegalStateException(AppModule.class.getCanonicalName() + " must be set");
      }
      if (dataSourceModule == null) {
        this.dataSourceModule = new DataSourceModule();
      }
      return new DaggerAppComponent(this);
    }

    public Builder appModule(AppModule appModule) {
      this.appModule = Preconditions.checkNotNull(appModule);
      return this;
    }

    public Builder dataSourceModule(DataSourceModule dataSourceModule) {
      this.dataSourceModule = Preconditions.checkNotNull(dataSourceModule);
      return this;
    }
  }
}
